language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - clang-3.8
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
script:
  - make
before_install:
- openssl enc -aes-256-cbc -d -in addNumbers.cpp.enc -out addNumbers.cpp -base64 -K $encrypted_d1234_key -iv $encrypted_d1234_iv

